# Generated by Django 5.0.7 on 2024-08-11 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_page', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
